// <auto-generated />
namespace Project_MVC_CF_Special.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class flajl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(flajl));
        
        string IMigrationMetadata.Id
        {
            get { return "202504020855373_flajl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
